require "./ps2_dissector"

module Citrine
  module Cradare2
    class R2PluginGenerator
      # Generates a comprehensive radare2 r2pipe/r2 script or configuration
      # that registers Citrine VM opcodes, types, GS privileged registers,
      # DMAC registers, SPRAM memory maps, print formats, and command macros.
      def self.generate_r2_script(target_path : String, source_map_path : String? = nil) : String
        io = IO::Memory.new
        io.puts "#!/usr/bin/env r2 -i"
        io.puts "# Radare2 Debug & Analysis Script for PlayStation 2 / Citrine"
        io.puts "# Generated by Citrine Toolkit"
        io.puts "o #{target_path}" unless target_path.empty?
        io.puts "e asm.arch = mips"
        io.puts "e asm.bits = 32"
        io.puts "e asm.cpu = mips3"
        io.puts "e asm.pseudo = true"
        io.puts "e asm.bytes = true"
        io.puts "e asm.flags = true"

        io.puts "\n# EE Memory Map Segments"
        io.puts "f mem.kuseg_cached   = 0x00000000"
        io.puts "f mem.kuseg_uncached = 0x20000000"
        io.puts "f mem.kuseg_accel    = 0x30000000"
        io.puts "f mem.kseg0          = 0x80000000"
        io.puts "f mem.kseg1          = 0xA0000000"

        io.puts "\n# Citrine PS2 SPRAM Memory Map flags (16KB Fast Scratchpad)"
        io.puts "f spram.start       = 0x70000000"
        io.puts "f spram.canary      = 0x70000000"
        io.puts "f spram.frame_count = 0x70000004"
        io.puts "f spram.vm_status   = 0x70000008"
        io.puts "f spram.end         = 0x70004000"
        io.puts "f spram.size        = 0x4000"

        io.puts "\n# Graphics Synthesizer (GS) Privileged Control Registers (0x12000000 - 0x12001080)"
        io.puts "f gs.framebuffer0 = 0x00000000 # Default Frame Buffer Base (FBP=0)"
        io.puts "f gs.pmode    = 0x12000000 # PCRTC Mode setting"
        io.puts "f gs.smode1   = 0x12000010 # Video sync/clock timings"
        io.puts "f gs.smode2   = 0x12000020 # Interlace & field/frame mode"
        io.puts "f gs.dispfb1  = 0x12000070 # Read Circuit 1 frame buffer base & width"
        io.puts "f gs.display1 = 0x12000080 # Read Circuit 1 display position & magnification"
        io.puts "f gs.dispfb2  = 0x12000090 # Read Circuit 2 frame buffer base & width"
        io.puts "f gs.display2 = 0x120000A0 # Read Circuit 2 display position & magnification"
        io.puts "f gs.bgcolor  = 0x120000E0 # Background border color"
        io.puts "f gs.csr      = 0x12001000 # GS System status & interrupt reset"
        io.puts "f gs.imr      = 0x12001010 # Interrupt mask register"
        io.puts "f gs.busdir   = 0x12001040 # Host interface bus direction"

        io.puts "\n# Direct Memory Access Controller (DMAC) Registers"
        io.puts "f dmac.chcr2  = 0x1000A000 # Channel 2 (GIF) Control Register"
        io.puts "f dmac.madr2  = 0x1000A010 # Channel 2 Memory Address"
        io.puts "f dmac.qwc2   = 0x1000A020 # Channel 2 Quadword Count"
        io.puts "f dmac.tadr2  = 0x1000A030 # Channel 2 Tag Address"
        io.puts "f dmac.d_ctrl = 0x1000E000 # DMAC Global Control"
        io.puts "f dmac.d_stat = 0x1000E010 # DMAC Status / Interrupt Flags"
        io.puts "f dmac.d_pcr  = 0x1000E020 # DMAC Priority Control"

        io.puts "\n# Citrine Dynamic Memory Layout Flags"
        io.puts "f mem.heap_start    = 0x00200000 # Citrine Dynamic Heap Start"
        io.puts "f mem.scratch_start = 0x00400000 # Per-frame Scratch Pool Start (Ring Buffer)"
        io.puts "f mem.scratch_end   = 0x00440000 # Per-frame Scratch Pool End (256 KB)"

        io.puts "\n# Print Formats (pf)"
        io.puts "pf.gs_pmode ww (qword)raw (dword)low (dword)high"
        io.puts "pf.gs_dispfb ww (qword)raw (dword)fbp_fbw_psm (dword)dbx_dby"
        io.puts "pf.gs_display ww (qword)raw (dword)dx_dy_mag (dword)dw_dh"
        io.puts "pf.giftag qq (qword)low_nloop_eop_flg (qword)high_regs"
        io.puts "pf.citrine_obj ii (dword)class_id (dword)field_count"

        io.puts "\n# Helper Macros"
        io.puts "(ps2_info; iI; iS; iE)"
        io.puts "(ps2_spram; pxw 32 @ 0x70000000)"
        io.puts "(ps2_canary_check; pxw 4 @ 0x70000000)"
        io.puts "(ps2_heap_check; pxw 32 @ 0x00200000)"
        io.puts "(ps2_scratch_check; pxw 32 @ 0x00400000)"
        io.puts "(ps2_obj_dump; pf.citrine_obj @ 0x00200000; pxw 16 @ 0x00200008)"
        io.puts "(ps2_regs; pxq 16 @ 0x12000000; pxq 16 @ 0x12001000)"
        io.puts "(ps2_dmac; pxw 16 @ 0x1000A000; pxw 16 @ 0x1000E000)"
        io.puts "(ps2_disasm; pd 8 @ 0x00100000; pd 20 @ 0x00100020)"

        if source_map_path && File.exists?(source_map_path)
          sm = SourceMap.from_file(source_map_path)
          io.puts "\n# Citrine Source Map Symbols"
          sm.locations.each do |offset, loc|
            byte_addr = offset * 4
            fn = loc.function ? "_#{loc.function}" : ""
            io.puts "f sym.citrine.line#{loc.line}#{fn} = #{byte_addr}"
            io.puts "CC #{File.basename(loc.file)}:#{loc.line} @ #{byte_addr}"
          end
        end

        io.to_s
      end

      # Installs the PS2 plugin script globally into user's ~/.radare2rc
      def self.install_global_rc : Bool
        rc_path = File.join(Path.home.to_s, ".radare2rc")
        marker = "# --- Citrine PS2 Plugin ---"
        script = generate_r2_script("")

        existing = File.exists?(rc_path) ? File.read(rc_path) : ""
        if existing.includes?(marker)
          # Replace section
          parts = existing.split(marker)
          updated = parts[0] + marker + "\n" + script + "\n" + marker + parts[2]? || ""
          File.write(rc_path, updated)
        else
          File.open(rc_path, "a") do |f|
            f.puts "\n#{marker}"
            f.puts script
            f.puts marker
          end
        end
        true
      rescue ex
        false
      end
    end
  end
end
