# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module B_PS2_HARDWARE
      # # PlayStation 2 Hardware Architecture
      #
      # The Sony PlayStation 2 possesses a unique asymmetrical architecture composed of the Emotion Engine
      # (R5900 MIPS core with 128-bit SIMD registers), Graphic Synthesizer, SPU2 sound processor, and IOP I/O processor.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Emotion Engine (EE) CPU</strong></td>
      #       <td><code>.topic_01_emotion_engine</code></td>
      #       <td>R5900 64-bit MIPS CPU clocked at 294.912 MHz with 128-bit multimedia registers.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>16KB Scratchpad RAM (SPRAM)</strong></td>
      #       <td><code>.topic_02_spram_mapping</code></td>
      #       <td>Zero-latency on-chip data memory located at physical address 0x70000000.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Graphic Synthesizer (GS)</strong></td>
      #       <td><code>.topic_03_graphic_synthesizer</code></td>
      #       <td>147.456 MHz rasterizer featuring 4MB embedded DRAM with 48 GB/s bandwidth.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - runtime/include/citrine_vm.h
      # - runtime/include/citrine_draw3d.h
      #
      module PS2_HARDWARE
        # **Emotion Engine (EE) CPU**: R5900 64-bit MIPS CPU clocked at 294.912 MHz with 128-bit multimedia registers.
        #
        # Citrine values are 16-byte aligned 128-bit quadwords (`Value`), allowing single-cycle DMA transfers
        # and vector transformations directly in hardware registers.
        #
        def self.topic_01_emotion_engine : Nil; end

        # **16KB Scratchpad RAM (SPRAM)**: Zero-latency on-chip data memory located at physical address 0x70000000.
        #
        # Citrine maps the active function register frame directly to the 16KB SPRAM at `0x70000000`.
        # This provides up to 1024 registers with zero cache miss penalties for high-speed game logic loops.
        #
        def self.topic_02_spram_mapping : Nil; end

        # **Graphic Synthesizer (GS)**: 147.456 MHz rasterizer featuring 4MB embedded DRAM with 48 GB/s bandwidth.
        #
        # The GS handles 2D primitives and 3D textured quads with hardware Z-buffering (ZBUF),
        # alpha blending, and color formats including PSMCT32 (32-bit RGBA) and PSMT8 (8-bit paletted).
        #
        def self.topic_03_graphic_synthesizer : Nil; end
      end
    end
  end
end
{% end %}
