# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module E_ASSET_PIPELINE
      # # Asset Pipeline & ISO Disc Generation
      #
      # Citrine converts modern 3D and multimedia assets into optimized PlayStation 2 binary formats
      # and masters bootable ISO9660 disc images (`.iso`).
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>3D Meshes (.obj, .gltf, .glb)</strong></td>
      #       <td><code>.topic_01_mesh_import</code></td>
      #       <td>Converts models to 16-byte aligned Citrine Binary Mesh (.cbm).</td>
      #     </tr>
      #     <tr>
      #       <td><strong>TTF & OTF Vector Font Rasterizer</strong></td>
      #       <td><code>.topic_02_font_rasterizer</code></td>
      #       <td>Bakes vector fonts into 256x256 GS texture atlases and Citrine Binary Font (.cbf) metrics.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>SPU2 ADPCM Audio (VAG)</strong></td>
      #       <td><code>.topic_03_audio_spu2</code></td>
      #       <td>4:1 compression encoding 28 16-bit PCM samples into 16-byte hardware ADPCM blocks.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Pure Crystal ISO9660 Builder</strong></td>
      #       <td><code>.topic_04_iso9660_mastering</code></td>
      #       <td>Generates bootable PS2 CD/DVD disc images without external dependencies.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/citrine/importers/mesh_importer.cr
      # - src/citrine/importers/font_importer.cr
      # - src/citrine/importers/image_importer.cr
      # - src/citrine/importers/sound_importer.cr
      # - src/citrine/iso/iso_builder.cr
      #
      module ASSET_PIPELINE
        # **3D Meshes (obj, gltf, glb)**: Converts models to 16-byte aligned Citrine Binary Mesh (.cbm).
        #
        # Vertices are packed into 32-byte interleaved records (Pos XYZ, Normal XYZ, UV) aligned
        # to 16-byte quadword boundaries for Emotion Engine GIF-DMA transfers.
        #
        def self.topic_01_mesh_import : Nil; end

        # **TTF & OTF Vector Font Rasterizer**: Bakes vector fonts into 256x256 GS texture atlases and Citrine Binary Font (.cbf) metrics.
        #
        # Offline rasterization converts TrueType bezier contours into textured quads, enabling
        # high-speed 60 FPS text rendering on the GS without runtime font engine overhead.
        #
        def self.topic_02_font_rasterizer : Nil; end

        # **SPU2 ADPCM Audio (VAG)**: 4:1 compression encoding 28 16-bit PCM samples into 16-byte hardware ADPCM blocks.
        #
        # PS2 SPU2 hardware decodes 16-byte VAG blocks directly. Citrine's sound importer compresses
        # WAV audio to fit within the 2MB Sound Memory limit.
        #
        def self.topic_03_audio_spu2 : Nil; end

        # **Pure Crystal ISO9660 Builder**: Generates bootable PS2 CD/DVD disc images without external dependencies.
        #
        # `Citrine::IsoBuilder` assembles PVD sector 16, Terminator sector 17, L/M Path tables,
        # and root directory records containing `SYSTEM.CNF`, `CITRINE.ELF`, and `GAME.CBC`.
        #
        def self.topic_04_iso9660_mastering : Nil; end
      end
    end
  end
end
{% end %}
