# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module C_VIRTUAL_MACHINE
      # # Citrine Virtual Machine Architecture
      #
      # Citrine VM executes fixed-width 32-bit instructions with a register-based architecture optimized for MIPS.
      # It enforces zero-allocation loops through frame bump allocators, avoiding Garbage Collector pauses.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>32-bit Opcode Encoding</strong></td>
      #       <td><code>.topic_01_instruction_encoding</code></td>
      #       <td>Compact 32-bit instruction format with 8-bit registers and 16-bit immediate fields.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Zero-GC Memory Arenas</strong></td>
      #       <td><code>.topic_02_zero_gc_arena</code></td>
      #       <td>Per-frame linear bump arenas reset every V-Blank interval.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - runtime/src/citrine_vm.c
      # - src/citrine/compiler/bytecode_compiler.cr
      #
      module VIRTUAL_MACHINE
        # **32-bit Opcode Encoding**: Compact 32-bit instruction format with 8-bit registers and 16-bit immediate fields.
        #
        # Instructions follow 3 primary encodings:
        # - `ABC`: 8-bit Opcode, 8-bit Reg Dest, 8-bit Reg A, 8-bit Reg B
        # - `AB_IMM`: 8-bit Opcode, 8-bit Reg Dest, 16-bit Immediate (Unsigned)
        # - `BRANCH`: 8-bit Opcode, 8-bit Reg Cond, 16-bit Relative Signed Offset
        #
        def self.topic_01_instruction_encoding : Nil; end

        # **Zero-GC Memory Arenas**: Per-frame linear bump arenas reset every V-Blank interval.
        #
        # Dynamic allocations inside the frame loop use the 64KB frame arena. At each `Citrine.begin_drawing`
        # call, the bump arena offset is reset to zero, ensuring constant 60 FPS frame times without GC pauses.
        #
        def self.topic_02_zero_gc_arena : Nil; end
      end
    end
  end
end
{% end %}
