# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module K_MODULAR_SUBSYSTEMS
      # # Require-Based Context DSL & Sequential Loop Shifts
      #
      # On the PlayStation 2's 32 MB Main RAM architecture, keeping every native subsystem and scene entity loaded
      # at all times is inefficient and causes memory exhaustion. A 2D title menu has zero need for 3D perspective cameras,
      # mesh vertex caches, or IPU video buffers.
      #
      # Citrine provides a Require-Driven Context DSL that pairs Crystal's native annotation syntax with sequential `main_loop`
      # execution and the `exit` control keyword.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Declarative Subsystem Inclusions</strong></td>
      #       <td><code>.topic_01_declarative_requires_and_blocks</code></td>
      #       <td>Annotated requires and block-scoped context definitions.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Breaking Up User Files</strong></td>
      #       <td><code>.topic_02_modular_user_files</code></td>
      #       <td>Recursive context inheritance for user-defined types and methods.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Context-Scoped Main Loops & 'exit'</strong></td>
      #       <td><code>.topic_03_sequential_loops_and_exit</code></td>
      #       <td>Safe transitions between frame loops via the exit keyword.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Compile-Time Static Safety Checks</strong></td>
      #       <td><code>.topic_04_compile_time_safety</code></td>
      #       <td>Static rejection of unmounted subsystems and cross-context references.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>PlayStation 2 Memory Compliance</strong></td>
      #       <td><code>.topic_05_ps2_memory_compliance</code></td>
      #       <td>DMA quiescence and zero-GC context arena reclamation.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/stubs/citrine.cr
      # - src/stubs/citrine/context.cr
      # - src/citrine/parser/dsl_parser.cr
      # - src/citrine/compiler/bytecode_compiler.cr
      # - runtime/src/citrine_vm.c
      #
      module CONTEXT_DSL_AND_MEMORY_SHIFTS
        # **Declarative Subsystem Inclusions**: Annotated requires and block-scoped context definitions.
        #
        # Subsystems and user files can be scoped to specific execution contexts using either single-line annotations or block groupings:
        #
        # ### 1. Single-Line Annotation (`@[Context(:name)]`)
        # ```crystal
        # require "citrine" # Resident base kernel
        #
        # @[Context(:menu)]
        # require "citrine/draw2d"
        #
        # @[Context(:game)]
        # require "citrine/draw3d"
        #
        # # Shared across multiple contexts:
        # @[Context(:menu, :game)]
        # require "citrine/audio"
        # ```
        #
        # ### 2. Block-Scoped Context Grouping (`context(:name) do ... end`)
        # ```crystal
        # context(:game) do
        #   require "citrine/draw3d"
        #   require "citrine/physics"
        #   require "./entities/player"
        #   require "./scenes/dungeon"
        # end
        # ```
        #
        def self.topic_01_declarative_requires_and_blocks : Nil; end

        # **Breaking Up User Files**: Recursive context inheritance for user-defined types and methods.
        #
        # When user files are required inside a context block, all types, structs, and methods defined within those files
        # automatically inherit that context:
        #
        # ```text
        # my_game/
        # ├── main.cr
        # ├── src/
        # │   ├── menu/title_screen.cr # Inherits :menu context
        # │   └── game/player.cr       # Inherits :game context
        # ```
        #
        # ```crystal
        # # main.cr
        # context(:menu) do
        #   require "citrine/draw2d"
        #   require "./src/menu/title_screen"
        # end
        #
        # context(:game) do
        #   require "citrine/draw3d"
        #   require "./src/game/player"
        # end
        # ```
        #
        def self.topic_02_modular_user_files : Nil; end

        # **Context-Scoped Main Loops & 'exit'**: Safe transitions between frame loops via the exit keyword.
        #
        # Context shifts are strictly forbidden *inside* a frame loop to prevent tearing mid-flight GIF DMA transfers
        # or corrupting GS rasterizer states. Transitions occur between sequential `main_loop` blocks using `exit`:
        #
        # ```crystal
        # loop do
        #   # 1. Menu Screen (Context: :menu inferred or explicit)
        #   menu = TitleScreen.new
        #   Citrine.main_loop(context: :menu) do
        #     menu.draw
        #     exit if menu.start_selected?
        #   end
        #
        #   # --- Context Shift occurs here: DMA sync + context_arena wipe ---
        #
        #   # 2. 3D Gameplay
        #   player = Player.new
        #   Citrine.main_loop(context: :game) do
        #     player.update
        #     player.draw
        #     exit if player.dead?
        #   end
        #
        #   # --- Context Shift occurs here: Gameplay memory wiped, Menu restored ---
        # end
        # ```
        #
        def self.topic_03_sequential_loops_and_exit : Nil; end

        # **Compile-Time Static Safety Checks**: Static rejection of unmounted subsystems and cross-context references.
        #
        # The Citrine compiler verifies all method calls and type instantiations against the active `main_loop` context:
        #
        # 1. **Subsystem Violation**: Calling `Draw3D.cube` inside `main_loop(context: :menu)` emits a compile error:
        #    ```text
        #    Subsystem violation: 'Draw3D.cube' requires 'citrine/draw3d', which is not mounted in active main_loop context ':menu'.
        #    ```
        #
        # 2. **Cross-Context Type Violation**: Instantiating a `:game` class inside `:menu`:
        #    ```text
        #    Context violation: Type 'Player' belongs to context(:game), which is not mounted in active main_loop context ':menu'.
        #    ```
        #
        # 3. **Top-Level Context Declaration Guard**: Defining `context(:name) do` inside `main_loop` is rejected:
        #    ```text
        #    Compile Error: Context declarations cannot be placed inside main_loop. Declare contexts at the top-level.
        #    ```
        #
        def self.topic_04_compile_time_safety : Nil; end

        # **PlayStation 2 Memory Compliance**: DMA quiescence and zero-GC context arena reclamation.
        #
        # Between `main_loop` executions, the Citrine VM executes the **Between-Loop Context Shift Protocol**:
        # 1. **DMA Quiescence**: Waits for GIF DMA Channel 2 and SPU2 DMA Channel 4 to finish all pending transfers (`Citrine_SyncDMA()`).
        # 2. **Cache Flush**: Synchronizes and invalidates Emotion Engine data caches (`SyncDCache()`).
        # 3. **Zero-GC Arena Reclamation**: Resets the 4 MB Context Arena (`vm->context_arena.offset = 0`).
        # 4. **Subsystem Mounting**: Updates `vm->active_subsystems` bitmask and loads incoming subsystem dispatch tables.
        #
        # **Result**: 100% of scene heap memory is reclaimed with zero garbage collection overhead and zero heap fragmentation across indefinite scene transitions.
        #
        def self.topic_05_ps2_memory_compliance : Nil; end
      end
    end
  end
end
{% end %}
