# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module K_MODULAR_SUBSYSTEMS
      # # 2D Texture Drawing DSL & PS2 Palette Swapping
      #
      # Citrine provides an expressive, idiomatic Crystal DSL for 2D texture drawing under `Citrine::Draw2D`.
      #
      # Moving beyond flat procedural calls with loose numeric arguments, the `draw_texture` DSL integrates natively with the
      # `Transform2D` affine matrix stack, offers arbitrary pivot rotation with anchor presets (`:center`, `:bottom_center`),
      # color modulation tinting, UV cropping (`Rect`), and directional mirroring (`flip_x`, `flip_y`).
      #
      # On the PlayStation 2 Graphics Synthesizer (GS), Citrine transparently routes axis-aligned unrotated draws to the hardware
      # `GS_PRIM_SPRITE` fast-path (2 vertices, zero CPU trigonometry). Furthermore, it provides native 8-bit CLUT (`PSMT8`)
      # palette swapping with hardware CSM1 swizzling, enabling instant character skinning and recoloring with zero eDRAM pixel duplication.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Idiomatic draw_texture DSL</strong></td>
      #       <td><code>.topic_01_draw_texture_dsl</code></td>
      #       <td>Fluent 2D texture drawing with named arguments and overloads</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Rotation & Origin Anchor Presets</strong></td>
      #       <td><code>.topic_02_rotation_and_pivots</code></td>
      #       <td>Arbitrary pivot rotation with anchor symbols and Vector2 offsets</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Affine Matrix Stack Integration</strong></td>
      #       <td><code>.topic_03_matrix_stack_integration</code></td>
      #       <td>Hierarchical scene rendering with Transform2D</td>
      #     </tr>
      #     <tr>
      #       <td><strong>UV Cropping & Directional Mirroring</strong></td>
      #       <td><code>.topic_04_uv_cropping_and_flipping</code></td>
      #       <td>Spritesheet slicing via Rect and clean flip_x / flip_y controls</td>
      #     </tr>
      #     <tr>
      #       <td><strong>PlayStation 2 CLUT Palette Swapping (PSMT8)</strong></td>
      #       <td><code>.topic_05_ps2_palette_swapping</code></td>
      #       <td>Zero-eDRAM duplication character skinning with CSM1 swizzling</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/stubs/citrine.cr
      # - src/stubs/citrine/draw2d.cr
      # - runtime/include/citrine_draw2d.h
      # - runtime/src/citrine_draw2d.c
      #
      module DRAW2D_TEXTURES
        # **Idiomatic draw_texture DSL**: Fluent 2D texture drawing with named arguments and overloads.
        #
        # Inside `Citrine.draw_2d do |d|` or directly via `Citrine::Draw2D`, developers can draw textures using clean,
        # expressive keyword arguments:
        # ```crystal
        # require "citrine"
        # require "citrine/draw2d"
        #
        # Citrine.draw_2d do |d|
        #   # Native dimensions, default coordinates
        #   d.draw_texture(hero_tex, 100, 50)
        #
        #   # Explicit dimensions and tint color
        #   d.draw_texture(hero_tex, 100, 50, width: 64, height: 64, tint: Color::White)
        #
        #   # Scale factor
        #   d.texture(hero_tex, 100, 50, scale: 2.0)
        # end
        # ```
        # The `Texture` struct also exposes `.draw(x, y, ...)` directly on the instance:
        # ```crystal
        # hero_tex.draw(100, 50, tint: Color::Red)
        # ```
        #
        def self.topic_01_draw_texture_dsl : Nil; end

        # **Rotation & Origin Anchor Presets**: Arbitrary pivot rotation with anchor symbols and Vector2 offsets.
        #
        # Rotating sprites requires specifying a rotation angle (in degrees) and a pivot point around which rotation occurs.
        # Citrine offers intuitive anchor presets as well as explicit `Vector2` coordinates:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Anchor Preset</th>
        #       <th>Relative Pivot Ratio</th>
        #       <th>Typical Use Case</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`:top_left` (default)</td>
        #       <td>`(0.0, 0.0)`</td>
        #       <td>UI icons, screen-space elements</td>
        #     </tr>
        #     <tr>
        #       <td>`:center`</td>
        #       <td>`(0.5, 0.5)`</td>
        #       <td>Rotating bullets, particles, coins, wheels</td>
        #     </tr>
        #     <tr>
        #       <td>`:bottom_center`</td>
        #       <td>`(0.5, 1.0)`</td>
        #       <td>Character sprites grounded on the floor</td>
        #     </tr>
        #     <tr>
        #       <td>`:top_center`</td>
        #       <td>`(0.5, 0.0)`</td>
        #       <td>Hanging ropes, chandeliers, ceiling traps</td>
        #     </tr>
        #     <tr>
        #       <td>`:bottom_left`</td>
        #       <td>`(0.0, 1.0)`</td>
        #       <td>Gauges, rotating levers</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # ```crystal
        # Citrine.draw_2d do |d|
        #   # Rotated around center pivot
        #   d.draw_texture(sword_tex, 200, 150, rotation: 45.0, origin: :center)
        #
        #   # Rotated around character feet
        #   d.draw_texture(character_tex, 300, 400, rotation: 15.0, origin: :bottom_center)
        #
        #   # Rotated around custom weapon hilt coordinates
        #   d.draw_texture(gun_tex, 100, 100, rotation: aim_angle, origin: Vector2.new(8, 12))
        # end
        # ```
        #
        def self.topic_02_rotation_and_pivots : Nil; end

        # **Affine Matrix Stack Integration**: Hierarchical scene rendering with Transform2D.
        #
        # All 2D texture operations fully respect `Draw2D.transform(...)`, `push_matrix`, and `pop_matrix`.
        # Child textures inherit parent translation, rotation, and scaling:
        # ```crystal
        # Citrine.draw_2d do |d|
        #   # Camera or container transform
        #   d.transform(x: 320, y: 240, rotation: camera_angle, scale: camera_zoom) do
        #     # (0, 0) is rendered in transformed camera space
        #     d.draw_texture(world_map_tex, 0, 0, origin: :center)
        #
        #     # Vehicle turret attached to chassis
        #     d.draw_texture(chassis_tex, 100, 100, origin: :center)
        #     d.transform(x: 100, y: 100, rotation: turret_angle) do
        #       d.draw_texture(turret_tex, 0, 0, origin: :center)
        #     end
        #   end
        # end
        # ```
        #
        def self.topic_03_matrix_stack_integration : Nil; end

        # **UV Cropping & Directional Mirroring**: Spritesheet slicing via Rect and clean flip_x / flip_y controls.
        #
        # Textures can be cropped to sub-rectangles (for texture atlases and spritesheets) using `src: Rect`:
        # ```crystal
        # Citrine.draw_2d do |d|
        #   # UV crop a 32x32 frame from an atlas
        #   frame_rect = Rect.new(32, 0, 32, 32)
        #   d.draw_texture(atlas_tex, 100, 100, src: frame_rect)
        #
        #   # Character facing left or right
        #   d.draw_texture(hero_tex, 100, 100, flip_x: facing_left, flip_y: false)
        # end
        # ```
        # The `Sprite` value struct also bundles a `Texture` with a source `Rect` for reusable frame handles:
        # ```crystal
        # icon = atlas_tex.crop(0, 0, 16, 16)
        # icon.draw(50, 50, rotation: 45.0, origin: :center)
        # ```
        #
        def self.topic_04_uv_cropping_and_flipping : Nil; end

        # **PlayStation 2 CLUT Palette Swapping (PSMT8)**: Zero-eDRAM duplication character skinning with CSM1 swizzling.
        #
        # On the PlayStation 2, the 4 MB embedded DRAM (eDRAM) must fit the front buffer, back buffer, Z-buffer,
        # and all active textures. Duplicating 32-bit textures for alternate character colors (e.g. 4-player multiplayer)
        # rapidly exhausts eDRAM.
        #
        # Citrine solves this with **8-bit Indexed Textures (`PSMT8`)**:
        # - Texture pixel data is 1 byte per pixel (**75% memory reduction**).
        # - Palettes (Color Look-Up Tables / CLUT) are 256 colors $\times$ 4 bytes = **1 KB**.
        # - Swapping character skins simply alters the GS `TEX0_1.CBP` (CLUT Buffer Pointer) in VRAM without re-uploading the texture pixels!
        #
        # #### Hardware CSM1 Swizzling
        # In GS `CSM1` mode, palette entries 8..15 and 16..23 within every 32-entry block must be swapped.
        # `Palette.swizzle_psmt8` performs this transformation automatically during upload:
        # ```crystal
        # p1_palette = Palette.load("rom0:HERO_P1.PAL")
        # p2_palette = Palette.load("rom0:HERO_P2.PAL")
        #
        # Citrine.draw_2d do |d|
        #   # Inline palette swap
        #   d.draw_texture(hero_tex, 100, 100, palette: p1_palette)
        #   d.draw_texture(hero_tex, 200, 100, palette: p2_palette)
        #
        #   # Block-scoped palette for multiple enemies
        #   d.with_palette(fire_palette) do
        #     d.draw_texture(mob_tex, 50, 100)
        #     d.draw_texture(boss_tex, 150, 100)
        #   end
        # end
        # ```
        #
        def self.topic_05_ps2_palette_swapping : Nil; end
      end
    end
  end
end
{% end %}
