# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module K_MODULAR_SUBSYSTEMS
      # # Modular Subsystems (Physics, UI, Scene, Hardware)
      #
      # Citrine enforces a strict modularity boundary: physics, immediate-mode GUI, scene management, camera controllers,
      # and low-level hardware coprocessors are kept out of the core runtime unless explicitly required.
      # When required via `require "citrine/<subsystem>"`, the module definitions are merged into the compilation unit.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>2D Fixed-Point Physics & Verlet Particles</strong></td>
      #       <td><code>.topic_01_physics_subsystem</code></td>
      #       <td>require "citrine/physics"</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Immediate-Mode UI (Raygui Style)</strong></td>
      #       <td><code>.topic_02_ui_subsystem</code></td>
      #       <td>require "citrine/ui"</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Scene Manager & Camera2D</strong></td>
      #       <td><code>.topic_03_scene_and_camera</code></td>
      #       <td>require "citrine/scene" and require "citrine/camera"</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Low-Level Emotion Engine Hardware Modules</strong></td>
      #       <td><code>.topic_04_hardware_modules</code></td>
      #       <td>VU0 Coprocessor 2, DMAC, GS registers, and CDVD disc sector streaming.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/stubs/citrine/physics.cr
      # - src/stubs/citrine/ui.cr
      # - src/stubs/citrine/scene.cr
      # - src/stubs/citrine/camera.cr
      # - src/stubs/citrine/hardware/vu0.cr
      # - src/stubs/citrine/hardware/dmac.cr
      # - src/stubs/citrine/hardware/gs.cr
      # - src/stubs/citrine/hardware/cdvd.cr
      #
      module MODULAR_SUBSYSTEMS
        # **2D Fixed-Point Physics & Verlet Particles**: require "citrine/physics".
        #
        # Import deterministic physics:
        # ```crystal
        # require "citrine/physics"
        #
        # # AABB Collision Check
        # colliding = Citrine::Physics2D.check_collision_recs(x1, y1, w1, h1, x2, y2, w2, h2)
        #
        # # Verlet Particle Dynamics
        # particle = Citrine::VerletParticle.new(320.0, 100.0)
        # particle.update(dt: 1.0, gravity: 0.35)
        # particle.constrain(20.0, 20.0, 620.0, 420.0, bounce: 0.75)
        # ```
        #
        def self.topic_01_physics_subsystem : Nil; end

        # **Immediate-Mode UI (Raygui Style)**: require "citrine/ui".
        #
        # Render Dear ImGui / Raygui-style immediate-mode interfaces on the PS2 with DualShock navigation:
        # ```crystal
        # require "citrine/ui"
        #
        # Citrine::UI.scope do |ui|
        #   ui.panel(140, 60, 360, 320, "SYSTEM CONFIGURATION")
        #   ui.label("Audio Volume:", 160, 96)
        #   volume = ui.slider_float("SFX", volume, 0.0, 1.0, 160, 116)
        #   rumble = ui.checkbox("Vibration", rumble, 160, 150)
        #   ui.progress_bar(hp, 100.0, 160, 240)
        #
        #   if ui.button("Apply", 160, 290)
        #     # Handled via Cross button when focused
        #   end
        # end
        # ```
        #
        def self.topic_02_ui_subsystem : Nil; end

        # **Scene Manager & Camera2D**: require "citrine/scene" and require "citrine/camera".
        #
        # Structure games with clean lifecycle hooks and camera tracking:
        # ```crystal
        # require "citrine/scene"
        # require "citrine/camera"
        #
        # cam = Camera2D.new(offset_x: 320.0, offset_y: 224.0, zoom: 1.0)
        # cam.follow(player_x, player_y, lerp_speed: 0.1)
        # ```
        #
        def self.topic_03_scene_and_camera : Nil; end

        # **Low-Level Emotion Engine Hardware Modules**: VU0 Coprocessor 2, DMAC, GS registers, and CDVD disc sector streaming.
        #
        # Access low-level PS2 hardware coprocessors:
        # - `require "citrine/hardware/vu0"`: Vector Unit 0 128-bit SIMD math.
        # - `require "citrine/hardware/dmac"`: Direct Memory Access Controller channels (GIF channel 2, SIF DMA).
        # - `require "citrine/hardware/gs"`: Low-level GS registers (PMODE, DISPFB, DISPLAY, CSR) & CLUT interleave.
        # - `require "citrine/hardware/cdvd"`: Disc sector reading (`sceCdRead`) and LBA conversions.
        #
        def self.topic_04_hardware_modules : Nil; end
      end
    end
  end
end
{% end %}
