# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module H_MEDIA_PIPELINE
      # # Flourite Universal Media Pipeline
      #
      # Citrine integrates Flourite (`sol-vin/flourite`), modern Crystal bindings for FFmpeg, to provide a zero-effort
      # media import pipeline. Any sound file (MP3, WAV, FLAC, OGG, AAC), video format (MP4, MKV, AVI, MOV), or image
      # can be transcoded into optimized PlayStation 2 native hardware formats with a single command.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>15 FPS Video Downsampling & The DVD Video Track Trick</strong></td>
      #       <td><code>.topic_01_video_optimization</code></td>
      #       <td>Optimizing FMVs to stream under 4x DVD-ROM transfer limits.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>SPU2 4-Bit ADPCM (VAG) Encoding</strong></td>
      #       <td><code>.topic_02_spu2_audio</code></td>
      #       <td>4:1 hardware compression saving 75% sound RAM.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>GS Paletted CLUT Textures</strong></td>
      #       <td><code>.topic_03_gs_clut_textures</code></td>
      #       <td>CLUT8 and CLUT4 color quantization for 4MB GS eDRAM.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/citrine/importers/flourite_media.cr
      # - src/citrine/cli/import_command.cr
      # - runtime/include/citrine_video.h
      # - runtime/include/citrine_audio.h
      #
      module MEDIA_PIPELINE
        # **15 FPS Video Downsampling & The DVD Video Track Trick**: Optimizing FMVs to stream under 4x DVD-ROM transfer limits.
        #
        # The PS2 DVD-ROM drive reads at 4x speed (~5.28 MB/s), but sustained real-time video streaming must not
        # starve the Emotion Engine or IOP DMA buffers.
        # - **15 FPS Downsampling:** Downsampling 30/60 FPS video to 15 FPS reduces data rates by 50-75% (to ~1.8 MB/s),
        #   allowing smooth MPEG-2 streaming to the IPU without disc read stuttering.
        # - **The DVD Video Track Trick:** Using `--dvd-track`, Citrine generates a sector-aligned MPEG-2 Program Stream
        #   (2048 bytes/sector) with GOP boundaries. This stream can be mapped into raw, unlisted DVD sectors outside
        #   the ISO9660 directory structure and streamed directly using low-level `sceCdRead` LBA sector calls,
        #   protecting FMVs from casual inspection and eliminating filesystem traversal overhead.
        #
        # ```bash
        # citrine import video intro.mp4 -o assets/intro.pss --fps 15 --dvd-track
        # ```
        #
        def self.topic_01_video_optimization : Nil; end

        # **SPU2 4-Bit ADPCM (VAG) Encoding**: 4:1 hardware compression saving 75% sound RAM.
        #
        # The PS2 Sound Processing Unit 2 (SPU2) features 2MB of dedicated sound memory. Citrine uses Flourite to resample
        # audio to 22.05kHz mono/stereo and encodes it into 16-byte Sony ADPCM blocks (28 4-bit nibbles per block).
        # This achieves 4:1 compression over 16-bit PCM, saving 75% of SPU2 RAM.
        # ```bash
        # citrine import audio bgm.mp3 -o assets/bgm.vag --rate 22050 --loop
        # ```
        #
        def self.topic_02_spu2_audio : Nil; end

        # **GS Paletted CLUT Textures**: CLUT8 and CLUT4 color quantization for 4MB GS eDRAM.
        #
        # The Graphics Synthesizer has only 4MB of embedded memory. 32-bit RGBA textures rapidly consume VRAM.
        # Citrine converts images to paletted indexed textures:
        # - **CLUT8 (PSMT8):** 1 byte per pixel + 256 color palette (75% VRAM savings).
        # - **CLUT4 (PSMT4):** 0.5 bytes per pixel + 16 color palette (87.5% VRAM savings).
        # ```bash
        # citrine import texture hero.png -o assets/hero.cbt --clut 8
        # ```
        #
        def self.topic_03_gs_clut_textures : Nil; end
      end
    end
  end
end
{% end %}
