# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module F_DEBUGGING
      # # Debugging with Radare2 & PCSX2
      #
      # Citrine integrates directly with radare2 and cradare2 for hardware-level debugging of PS2 Emotion Engine
      # registers, Scratchpad RAM, and PCSX2 GDB stub emulation.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Radare2 (r2) Integration</strong></td>
      #       <td><code>.topic_01_r2_debugging</code></td>
      #       <td>Automatic r2 script generation with MIPS R5900 arch, SPRAM flags, and custom macros.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>PCSX2 GDB Stub</strong></td>
      #       <td><code>.topic_02_pcsx2_gdb</code></td>
      #       <td>Live interactive breakpoints and variable inspection on port 1234.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/citrine/cli/debug_command.cr
      # - src/citrine/cradare2/plugin.cr
      #
      module DEBUGGING
        # **Radare2 (r2) Integration**: Automatic r2 script generation with MIPS R5900 arch, SPRAM flags, and custom macros.
        #
        # Running `citrine debug game.cbc` configures radare2 with:
        # - Architecture: `e asm.arch = mips`, `e asm.cpu = r5900`
        # - SPRAM base flag: `f spram.start = 0x70000000`
        # - GS Framebuffer flags: `f gs.framebuffer0 = 0x00000000`
        # - Macro `(spram <idx>)`: Inspects 16-byte aligned QWORD SPRAM registers
        # - Macro `(ee_regs)`: Displays Emotion Engine 128-bit general purpose registers
        #
        def self.topic_01_r2_debugging : Nil; end

        # **PCSX2 GDB Stub**: Live interactive breakpoints and variable inspection on port 1234.
        #
        # Start PCSX2 with the GDB server enabled, then attach radare2:
        # ```bash
        # r2 -d gdb://127.0.0.1:1234 -i citrine_r2.rc
        # ```
        # Step through instructions, inspect memory maps, and verify bytecode execution in real-time.
        #
        def self.topic_02_pcsx2_gdb : Nil; end
      end
    end
  end
end
{% end %}
