# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module J_METAPROGRAMMING
      # # PS2 Metaprogramming, Macros & ECS
      #
      # Citrine features a compile-time Crystal macro preprocessor (`MacroExpander`) that expands user-defined macros,
      # component-entity-system layouts, and finite state machines directly into standard Crystal AST prior to bytecode emission.
      # This allows zero-overhead metaprogramming without modifying the PlayStation 2 VM inner loop.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Custom Crystal Macros</strong></td>
      #       <td><code>.topic_01_crystal_macros</code></td>
      #       <td>Inlining math, coordinate clamping, and custom code generation.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Declarative ECS Memory Layout</strong></td>
      #       <td><code>.topic_02_ecs_macro</code></td>
      #       <td>citrine_ecs! component declarations.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Finite State Machine DSL</strong></td>
      #       <td><code>.topic_03_fsm_macro</code></td>
      #       <td>fsm! state transitions and integer jump tables.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Zero-Cost Release Stripping</strong></td>
      #       <td><code>.topic_04_release_stripping</code></td>
      #       <td>citrine compile --release dead code elimination.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/citrine/compiler/macro_expander.cr
      # - src/citrine/parser/dsl_parser.cr
      # - examples/11_macro_ecs_showcase/main.cr
      #
      module METAPROGRAMMING
        # **Custom Crystal Macros**: Inlining math, coordinate clamping, and custom code generation.
        #
        # Define Crystal macros with standard `macro` blocks and call them with arguments. The Citrine AST expander
        # performs argument substitution and inlines the resulting expressions:
        #
        # ```crystal
        # macro clamp_bound(val, min_v, max_v)
        #   if \{{val}} < \{{min_v}}
        #     \{{min_v}}
        #   elsif \{{val}} > \{{max_v}}
        #     \{{max_v}}
        #   else
        #     \{{val}}
        #   end
        # end
        #
        # player_x = clamp_bound(player_x, 20.0, 600.0)
        # ```
        #
        def self.topic_01_crystal_macros : Nil; end

        # **Declarative ECS Memory Layout**: citrine_ecs! component declarations.
        #
        # Declare components with `citrine_ecs!`. It emits sequential component ID constants and totals:
        #
        # ```crystal
        # citrine_ecs! do
        #   component Position, x: Float32, y: Float32
        #   component Velocity, vx: Float32, vy: Float32
        #   component Health, hp: Int32
        # end
        # # Emits: COMPONENT_POSITION = 1, COMPONENT_VELOCITY = 2, COMPONENT_HEALTH = 3, TOTAL_COMPONENTS = 3
        # ```
        #
        def self.topic_02_ecs_macro : Nil; end

        # **Finite State Machine DSL**: fsm! state transitions and integer jump tables.
        #
        # Declare entity behavior states with `fsm!`:
        #
        # ```crystal
        # fsm PlayerAI, initial: :idle do
        #   state :idle
        #   state :moving
        #   state :attacking
        # end
        #
        # # Generates STATE_IDLE, STATE_MOVING, STATE_ATTACKING and player_ai_state = 0
        # ```
        #
        def self.topic_03_fsm_macro : Nil; end

        # **Zero-Cost Release Stripping**: citrine compile --release dead code elimination.
        #
        # Build production ship discs with `--release`:
        # ```bash
        # citrine compile src/main.cr -o build/game.cbc --release
        # citrine iso src/main.cr -o build/game.iso --release
        # ```
        # All calls to `Citrine.log` and `Citrine.debug_overlay=` are eliminated from the AST, `.cbcsym` debug symbol
        # files are omitted, and string constants are pruned from the `.cbc` binary.
        #
        def self.topic_04_release_stripping : Nil; end
      end
    end
  end
end
{% end %}
