# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module D_RAYLIB_API
      # # Raylib-style PlayStation 2 API
      #
      # Citrine provides an ergonomic Raylib-inspired API in Crystal that maps directly to hardware registers
      # and Graphic Synthesizer DMA packets on the PlayStation 2.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>2D Shape & Text Rendering</strong></td>
      #       <td><code>.topic_01_rendering_2d</code></td>
      #       <td>Drawing rectangles, circles, lines, triangles, and bitmap fonts.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>3D Camera & Mesh Rendering</strong></td>
      #       <td><code>.topic_02_rendering_3d</code></td>
      #       <td>Perspective projection, floor grids, 3D cubes, and indexed meshes.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>DualShock 2 Gamepad & Vibration</strong></td>
      #       <td><code>.topic_03_dualshock_input</code></td>
      #       <td>Digital buttons, analog sticks, and force-feedback rumble motors.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/stubs/citrine.cr
      # - runtime/include/citrine_draw2d.h
      # - runtime/include/citrine_draw3d.h
      #
      module RAYLIB_API
        # **2D Shape & Text Rendering**: Drawing rectangles, circles, lines, triangles, and bitmap fonts.
        #
        # ```crystal
        # Citrine.begin_drawing
        # Citrine.clear_background(Color::Black)
        # Citrine.draw_rectangle(50, 50, 100, 80, Color::Red)
        # Citrine.draw_circle(200, 100, 30, Color::Yellow)
        # Citrine.draw_text("Hello PS2", 50, 200, 16, Color::White)
        # Citrine.end_drawing
        # ```
        #
        def self.topic_01_rendering_2d : Nil; end

        # **3D Camera & Mesh Rendering**: Perspective projection, floor grids, 3D cubes, and indexed meshes.
        #
        # ```crystal
        # cam = Camera3D.new(position: Vector3.new(0, 5, 10), target: Vector3.new(0, 0, 0))
        # Citrine.begin_mode_3d(cam)
        # Citrine.draw_grid(10, 1.0)
        # Citrine.draw_cube(0, 1, 0, 2, 2, 2, Color::Blue)
        # Citrine.draw_cube_wires(0, 1, 0, 2.1, 2.1, 2.1, Color::Yellow)
        # Citrine.end_mode_3d
        # ```
        #
        def self.topic_02_rendering_3d : Nil; end

        # **DualShock 2 Gamepad & Vibration**: Digital buttons, analog sticks, and force-feedback rumble motors.
        #
        # ```crystal
        # if Citrine.button_down?(Button::Cross)
        #   Citrine.set_rumble(128_u8, 0_u8) # Small motor
        # end
        # lx = Citrine.get_analog(0) # Left Stick X (-1.0 to 1.0)
        # ly = Citrine.get_analog(1) # Left Stick Y (-1.0 to 1.0)
        # ```
        #
        def self.topic_03_dualshock_input : Nil; end
      end
    end
  end
end
{% end %}
