# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module G_CONCURRENCY
      # # Cooperative Concurrency & CSP Channels
      #
      # Citrine implements a high-performance, cooperative fiber scheduler and CSP (Communicating Sequential Processes)
      # channel architecture tailored specifically for the PlayStation 2 Emotion Engine. With zero dynamic heap allocations,
      # deterministic context switches, and static register budgeting, Citrine allows developers to write clean, concurrent
      # game entity code and background worker pools without risking frame drops or garbage collection stalls.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Fiber Architecture & Context Switching</strong></td>
      #       <td><code>.topic_01_fiber_architecture</code></td>
      #       <td>Zero-GC cooperative fibers with pre-allocated register state.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Bounded CSP Channels</strong></td>
      #       <td><code>.topic_02_csp_channels</code></td>
      #       <td>Lock-free ring buffer communication between fibers.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Safety Checker, Watchdogs & Pitfalls</strong></td>
      #       <td><code>.topic_03_safety_and_pitfalls</code></td>
      #       <td>Hardware limits, watchdog timeouts, and common concurrency pitfalls.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - runtime/include/citrine_vm.h
      # - runtime/src/citrine_vm.c
      # - src/citrine/compiler/bytecode_compiler.cr
      # - src/citrine/compiler/budget_checker.cr
      # - src/stubs/citrine.cr
      #
      module CONCURRENCY
        # **Fiber Architecture & Context Switching**: Zero-GC cooperative fibers with pre-allocated register state.
        #
        # The Citrine scheduler supports up to 64 concurrent fibers (configurable up to 256). Each fiber has:
        # - 64 pre-allocated 128-bit QWORD saved registers (`Value saved_regs[64]`).
        # - Call frame stack for nested subroutines up to 16 depth.
        # - Cooperative yielding via `Citrine.yield` or `Citrine.sleep(seconds)`.
        #
        # ```crystal
        # # Spawning autonomous entity fibers
        # Citrine.spawn do
        #   while true
        #     # AI logic or background task
        #     Citrine.yield
        #   end
        # end
        # ```
        #
        # Context switches occur in sub-microsecond cycles by swapping the Emotion Engine SPRAM register window.
        #
        def self.topic_01_fiber_architecture : Nil; end

        # **Bounded CSP Channels**: Lock-free ring buffer communication between fibers.
        #
        # Fibers communicate without shared mutable state using CSP channels:
        # ```crystal
        # channel = Citrine::Channel(Int32).new(32)
        #
        # Citrine.spawn do
        #   channel.send(42)
        # end
        #
        # # In main thread or worker:
        # if msg = channel.try_receive
        #   puts "Received: #{msg}"
        # end
        # ```
        # All channel message buffers are pre-allocated statically in a 32-element ring buffer. Sending or receiving never triggers heap allocation.
        #
        def self.topic_02_csp_channels : Nil; end

        # **Safety Checker, Watchdogs & Pitfalls**: Hardware limits, watchdog timeouts, and common concurrency pitfalls.
        #
        # **Critical Pitfalls to Avoid:**
        # 1. **Tight Non-Yielding Loops:** A fiber that loops without calling `Citrine.yield` or `Citrine.sleep` will starve all other fibers. Citrine enforces an **Instruction Watchdog** of 5,000,000 instructions per frame—exceeding this triggers a hardware panic.
        # 2. **Channel Capacity Exceeded:** Sending to a full channel with `channel.send` when full will yield the fiber until a slot is freed.
        # 3. **SPRAM Register Overflow:** The static budget checker verifies that maximum concurrent fibers multiplied by peak register footprints fit within safe Emotion Engine memory boundaries.
        #
        def self.topic_03_safety_and_pitfalls : Nil; end
      end
    end
  end
end
{% end %}
