# ==============================================================================
# Citrine::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  # The `Citrine::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 6 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>GETTING_STARTED</code></td>
  #       <td><strong>Getting Started with Citrine PS2</strong></td>
  #       <td>Complete introduction to the Crystal VM and Raylib-style PlayStation 2 toolkit.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 2. Ps2 hardware (`B_PS2_HARDWARE`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>PS2_HARDWARE</code></td>
  #       <td><strong>PlayStation 2 Hardware Architecture</strong></td>
  #       <td>In-depth guide to the Emotion Engine, Scratchpad RAM, and Graphic Synthesizer.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 3. Virtual machine (`C_VIRTUAL_MACHINE`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>VIRTUAL_MACHINE</code></td>
  #       <td><strong>Citrine Virtual Machine Architecture</strong></td>
  #       <td>Direct-threaded bytecode interpreter, register windows, and zero-GC memory model.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 4. Raylib api (`D_RAYLIB_API`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>RAYLIB_API</code></td>
  #       <td><strong>Raylib-style PlayStation 2 API</strong></td>
  #       <td>Guide to 2D and 3D graphics, DualShock 2 input, and SPU2 audio playback.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 5. Asset pipeline (`E_ASSET_PIPELINE`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>ASSET_PIPELINE</code></td>
  #       <td><strong>Asset Pipeline & ISO Disc Generation</strong></td>
  #       <td>Importers for 3D meshes (OBJ, glTF, GLB), fonts (TTF, OTF, FNT), textures, audio, and ISO9660 mastering.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 6. Debugging (`F_DEBUGGING`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>DEBUGGING</code></td>
  #       <td><strong>Debugging with Radare2 & PCSX2</strong></td>
  #       <td>Disassembly, SPRAM memory inspection, GDB stub debugging, and symbol exploration.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Citrine PlayStation 2 Toolkit Commands:
    # ```bash
    # citrine run examples/01_hello_pad/main.cr
    # citrine iso examples/05_hello_world/main.cr
    # citrine debug examples/01_hello_pad/game.cbc
    # citrine ui
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::GETTING_STARTED`: **Getting Started with Citrine PS2** &mdash; Complete introduction to the Crystal VM and Raylib-style PlayStation 2 toolkit.
    #
    # ##### 2. Ps2 hardware (`B_PS2_HARDWARE`)
    # - `B_PS2_HARDWARE::PS2_HARDWARE`: **PlayStation 2 Hardware Architecture** &mdash; In-depth guide to the Emotion Engine, Scratchpad RAM, and Graphic Synthesizer.
    #
    # ##### 3. Virtual machine (`C_VIRTUAL_MACHINE`)
    # - `C_VIRTUAL_MACHINE::VIRTUAL_MACHINE`: **Citrine Virtual Machine Architecture** &mdash; Direct-threaded bytecode interpreter, register windows, and zero-GC memory model.
    #
    # ##### 4. Raylib api (`D_RAYLIB_API`)
    # - `D_RAYLIB_API::RAYLIB_API`: **Raylib-style PlayStation 2 API** &mdash; Guide to 2D and 3D graphics, DualShock 2 input, and SPU2 audio playback.
    #
    # ##### 5. Asset pipeline (`E_ASSET_PIPELINE`)
    # - `E_ASSET_PIPELINE::ASSET_PIPELINE`: **Asset Pipeline & ISO Disc Generation** &mdash; Importers for 3D meshes (OBJ, glTF, GLB), fonts (TTF, OTF, FNT), textures, audio, and ISO9660 mastering.
    #
    # ##### 6. Debugging (`F_DEBUGGING`)
    # - `F_DEBUGGING::DEBUGGING`: **Debugging with Radare2 & PCSX2** &mdash; Disassembly, SPRAM memory inspection, GDB stub debugging, and symbol exploration.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::GETTING_STARTED`: **Getting Started with Citrine PS2** &mdash; Complete introduction to the Crystal VM and Raylib-style PlayStation 2 toolkit.
    #
    # ##### `B_PS2_HARDWARE`
    # - `B_PS2_HARDWARE::PS2_HARDWARE`: **PlayStation 2 Hardware Architecture** &mdash; In-depth guide to the Emotion Engine, Scratchpad RAM, and Graphic Synthesizer.
    #
    # ##### `C_VIRTUAL_MACHINE`
    # - `C_VIRTUAL_MACHINE::VIRTUAL_MACHINE`: **Citrine Virtual Machine Architecture** &mdash; Direct-threaded bytecode interpreter, register windows, and zero-GC memory model.
    #
    # ##### `D_RAYLIB_API`
    # - `D_RAYLIB_API::RAYLIB_API`: **Raylib-style PlayStation 2 API** &mdash; Guide to 2D and 3D graphics, DualShock 2 input, and SPU2 audio playback.
    #
    # ##### `E_ASSET_PIPELINE`
    # - `E_ASSET_PIPELINE::ASSET_PIPELINE`: **Asset Pipeline & ISO Disc Generation** &mdash; Importers for 3D meshes (OBJ, glTF, GLB), fonts (TTF, OTF, FNT), textures, audio, and ISO9660 mastering.
    #
    # ##### `F_DEBUGGING`
    # - `F_DEBUGGING::DEBUGGING`: **Debugging with Radare2 & PCSX2** &mdash; Disassembly, SPRAM memory inspection, GDB stub debugging, and symbol exploration.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/getting_started"
require "./docs/b_ps2_hardware/ps2_hardware"
require "./docs/c_virtual_machine/virtual_machine"
require "./docs/d_raylib_api/raylib_api"
require "./docs/e_asset_pipeline/asset_pipeline"
require "./docs/f_debugging/debugging"

alias CitrineDocs = ::Citrine::Docs
{% end %}
