# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module I_TESTING_SUITE
      # # PS2 Hardware Testing Suite & Spec DSL
      #
      # Citrine introduces a first-class testing suite DSL (`Citrine::Spec`) designed specifically for PlayStation 2 development.
      # The test runner executes tests by compiling code into bytecode, building a bootable ISO, and supervising PCSX2 execution
      # in headless batch mode with millisecond assertion checks.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Hardware Assertion Matchers</strong></td>
      #       <td><code>.topic_01_spec_dsl</code></td>
      #       <td>Matchers for boot cleanliness, SPRAM canaries, and hardware panics.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Running Tests</strong></td>
      #       <td><code>.topic_02_test_command</code></td>
      #       <td>The citrine test CLI command.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/citrine/spec/ps2_spec.cr
      # - src/citrine/cli/test_command.cr
      # - src/citrine/debugger/pcsx2_bridge.cr
      # - src/citrine/debugger/crash_analyzer.cr
      #
      module TESTING_SUITE
        # **Hardware Assertion Matchers**: Matchers for boot cleanliness, SPRAM canaries, and hardware panics.
        #
        # Tests use custom hardware matchers:
        # - `should_boot_cleanly`: Asserts that the game initializes without VM panic or kernel exception.
        # - `should_preserve_spram`: Asserts that the SPRAM stack canary (`0xDEADBEEF`) remains uncorrupted.
        # - `should_have_output(text)`: Validates that EEConsole logs contain expected telemetry.
        # - `should_panic_with(msg)`: Validates deliberate panic paths (e.g. testing error boundaries).
        #
        # ```crystal
        # require "citrine/spec/ps2_spec"
        #
        # ps2_spec "Player Movement & SPRAM Safety" do |t|
        #   t.target("examples/01_hello_world/main.cr")
        #   result = t.boot_pcsx2(timeout: 2.seconds)
        #   result.should_boot_cleanly
        #   result.should_preserve_spram
        # end
        # ```
        #
        def self.topic_01_spec_dsl : Nil; end

        # **Running Tests**: The citrine test CLI command.
        #
        # Execute test suites individually or across entire directories:
        # ```bash
        # # Run all PS2 specs
        # citrine test spec/ps2/
        #
        # # Run an individual spec
        # citrine test spec/ps2/examples_ps2_spec.cr
        # ```
        #
        def self.topic_02_test_command : Nil; end
      end
    end
  end
end
{% end %}
