# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Citrine
  module Docs
    module A_GETTING_STARTED
      # # Getting Started with Citrine PS2
      #
      # Citrine is a Crystal game development toolkit and virtual machine targeting the Sony PlayStation 2 (PS2).
      # It enables writing modern Crystal code using an ergonomic Raylib-style API and executing it directly on
      # the PS2 Emotion Engine (R5900 @ 294MHz) and Graphic Synthesizer (GS 4MB eDRAM).
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Quickstart Guide</strong></td>
      #       <td><code>.topic_01_quickstart</code></td>
      #       <td>Compile and run your first PlayStation 2 game.</td>
      #     </tr>
      #     <tr>
      #       <td><strong>Opal Terminal Dashboard</strong></td>
      #       <td><code>.topic_02_tui_dashboard</code></td>
      #       <td>Interactive terminal dashboard for project telemetry and budget auditing.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/citrine.cr
      # - src/citrine/runner/runner.cr
      #
      module GETTING_STARTED
        # **Quickstart Guide**: Compile and run your first PlayStation 2 game.
        #
        # To compile and boot any Citrine game in the PCSX2 emulator:
        # ```bash
        # citrine run examples/01_hello_world/main.cr
        # ```
        # This automatically compiles the Crystal code into compact Citrine Bytecode (`.cbc`),
        # packages it into an ISO9660 disc image (`game.iso`), and launches PCSX2.
        #
        def self.topic_01_quickstart : Nil; end

        # **Opal Terminal Dashboard**: Interactive terminal dashboard for project telemetry and budget auditing.
        #
        # Launch the interactive terminal UI dashboard powered by Opal:
        # ```bash
        # citrine ui
        # ```
        # Explore examples, audit SPRAM budgets, inspect functions, and test controller inputs.
        #
        def self.topic_02_tui_dashboard : Nil; end
      end
    end
  end
end
{% end %}
